<?php

/**
* Implementation of hook_theme().
*/
function openlayers_kml_theme() {
  return array(
    // Themes for the formatters.
    'openlayers_kml_formatter_kml_openlayers' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}
 
/**
* Implementation of hook_field_formatter_info().
*
* All fields should have a 'default' formatter.
* Any number of other formatters can be defined as well.
* It's nice for there always to be a 'plain' option
* for the raw value, but that is not required.
*
*/
function openlayers_kml_field_formatter_info() {
  return array(
    // The machine name of the formatter.
    'kml_openlayers' => array(
      // The human-readable label shown on the Display
      // fields screen.
      'label' => t('KML OpenLayers Map'),
      // An array of the field types this formatter
      // can be used on.
      'field types' => array('filefield'),
      // CONTENT_HANDLE_CORE:   CCK will pass the formatter
      // a single value.
      // CONTENT_HANDLE_MODULE: CCK will pass the formatter
      // an array of all the values. None of CCK's core
      // formatters use multiple values, that is an option
      // available to other modules that want it.
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
  );
}
 
 
/**
* Theme function for 'default' example field formatter.
*
* $element['#item']: the sanitized $delta value for the item,
* $element['#field_name']: the field name,
* $element['#type_name']: the $node->type,
* $element['#formatter']: the $formatter_name,
* $element'#node']: the $node,
* $element['#delta']: the delta of this item, like '0',
*
*/
function theme_openlayers_kml_formatter_kml_openlayers($element) {
  // In here, find the KML field, make your map array, and render
	global $base_url;
	$kml = $base_url . '/' . $element['#item']['filepath'];

	//dsm($element);

	/*
	$map = openlayers_get_default_map();
  // Put together map
  $map['id'] = 'kml';
  // Make sure that our display projection matches the database projection
  $map['options']['displayProjection'] = ($field['srid'] != 0) ? $field['srid'] : '4326';
  */

	// TODO have formatter for each preset
	$preset = openlayers_get_preset('new');
	$map = $preset['preset_data'];

  //$map['controls']['SelectFeature'] = array('kml_example');

  // Adds KML Layer
	$map['layers']['kml_example'] = array(
		'id' => 'openlayers_kml_cck',
		'type' => 'KML',
		'name' => t('KML Overlay'),
		'url' => $kml,
	);

  // Adds fullscreen button
	$map['behaviors'] = array(
		'fullscreen' => array(
		  'id' => 'fullscreen',
		  'type' => 'openlayers_behaviors_fullscreen',
		  'layer' => 'kml_example',
		),
		// Use the 'name' attrib from the KML file as tooltip
		'openlayers_views_tooltip_id' => array(
				'id' => 'openlayers_views_tooltip_id',
				'type' => 'openlayers_behaviors_tooltip',
				'layer' => 'kml_example',
				//'attribute' => 'Description', // could use description instead 
			),
	);
  // Render Map
  $rendered_map = openlayers_render_map($map);

	return $rendered_map['themed'];
}
