<?php


/**
 * Implementation of hook_openlayers_behaviors
 */
function openlayers_kml_openlayers_behaviors() {
  return array(
    'openlayers_kml_vector_layer' => array(
       'title' => t('Dynamic Vector Layer for KML'),
       'description' => t('Adds a dynamic layer from a features array'),
       'type' => 'layer',
       'path' => drupal_get_path('module', 'openlayers_kml') 
         .'/includes/behaviors',
       'file' => 'openlayers_kml_vector_layer.inc',
       'ui_visibility' => FALSE,
       'behavior' => array(
         'class' => 'openlayers_kml_vector_layer',
         'parent' => 'openlayers_behavior',
       ),
    ),
   );
}


/**
* Implementation of hook_theme().
*/
function openlayers_kml_theme() {
/*
  // Create formatter theme functions
  foreach (openlayers_get_presets() as $name => $title) {
    $themes['openlayers_kml_formatter_openlayers_map_' . $name] = array(
      'arguments' => array('element' => NULL),
      'function' => 'theme_openlayers_kml_formatter_kml_openlayers',
    );
  }
*/
  $themes = array(
    'openlayers_kml_formatter_default' => array(
      'arguments' => array('element' => NULL),
      'function' => 'theme_openlayers_kml_formatter_map',
    ),
  );

  return $themes;
}
 
/**
* Implementation of hook_field_formatter_info().
*
* All fields should have a 'default' formatter.
* Any number of other formatters can be defined as well.
* It's nice for there always to be a 'plain' option
* for the raw value, but that is not required.
*
*/
function openlayers_kml_field_formatter_info() {
/*
  $formatters = array();

  // Map preset formatter
  foreach (openlayers_get_presets() as $name => $title) {
    $formatters['openlayers_map_' . $name] = array(
      'label' => t('OpenLayers Map: @preset', array('@preset' => check_plain($title))),
      'field types' => array('filefield'),
      'multiple values' => CONTENT_HANDLE_CORE,
    );
  }
  return $formatters;
*/

  $formatters = array();

  // Default formatter
  $formatters['default'] = array(
    'label' => t('Default Map'),
    'field types' => array('filefield'),
    'multiple values' => CONTENT_HANDLE_MODULE,
  );
 /* 
  // WKT value
  $formatters['openlayers_wkt'] = array(
    'label' => t('WKT Value'),
    'field types' => array('filefield'),
    'multiple values' => CONTENT_HANDLE_MODULE,
  );
*/
/*
  // Map preset formatter
  foreach (openlayers_preset_options() as $name => $title) {
    $formatters['openlayers_map_' . $name] = array(
      'label' => t('OpenLayers Map: @preset', 
        array('@preset' => check_plain($title))),
      'field types' => array('openlayers_filefield'),
      'multiple values' => CONTENT_HANDLE_MODULE,
    );
  }
*/
  return $formatters;
}

// NEW 2.x
function theme_openlayers_kml_formatter_map($element) {
  // Get the url of the KML file
  global $base_url;
  $kml = $base_url . '/' . $element[0]['#item']['filepath']; // TODO handle multiple files

// copied from theme_openlayers_cck_formatter_map

  $features = array();
  $field = content_fields($element['#field_name'], $element['#type_name']);
  $widget = $field['widget'];

  // Create array of $features
  foreach (element_children($element) as $delta) {
    $features[] = array(
      // First look for geo_field data, then for openlayers wkt data
/*
      'wkt' => $element[$delta]['#item']['openlayers_wkt'],
      'projection' => '4326',
*/
      'kml' => $kml,
      'projection' => '4326',

    );
  }


  // Get preset name from formatter. Strip off 'openlayers_cck_formatter_'
  // and 'openlayers_map_' from the beginning.
  // If none found, use default map.
  // TODO: Better way to do this?
/*
  if (drupal_substr($element['#formatter'], 25) == 'openlayers_cck_formatter_') {
    $preset_name = drupal_substr($element['#formatter'], 25);
  }
  elseif (drupal_substr($element['#formatter'], 0, 15) == 'openlayers_map_') {
    $preset_name = drupal_substr($element['#formatter'], 15);
  }
  else {
*/
// Just use default preset for now...
    $preset_name = variable_get('openlayers_default_preset', 'default');
  //}

  // Get map preset
  $preset = openlayers_preset_load($preset_name);

  // Add vector layer behavior
  $preset->data['behaviors']['openlayers_kml_vector_layer'] =
    array('features' => $features);

  // Add widget/formatter behaviors
  if (isset($widget['openlayers_behaviors']) && is_array($widget['openlayers_behaviors'])) {
    foreach ($widget['openlayers_behaviors'] as $key => $behavior) {
      if ($behavior['enabled']) {
        $preset->data['behaviors'][$key] = $behavior['options'];
      }
    }
  }

  // Render map
  return openlayers_render_map($preset->data, $preset->name);

///
}

/** OLD 1.x
 * Theme function for openlayers_kml element
 */
function theme_openlayers_kml_formatter_kml_openlayers($element) {
  // In here, find the KML field, make your map array, and render
  global $base_url;
  $kml = $base_url . '/' . $element['#item']['filepath'];

  // Get the preset that was chosen in display fields
  if (substr($element['#formatter'], 25) == 'openlayers_kml_formatter_') $preset_name = substr($element['#formatter'], 25);
  if (substr($element['#formatter'], 0, 15) == 'openlayers_map_') $preset_name = substr($element['#formatter'], 15);

  $preset = openlayers_get_preset($preset_name);
  $map = $preset['preset_data'];

  // Adds KML Layer
  $map['layers']['kml_example'] = array(
    'id' => 'openlayers_kml_cck',
    'type' => 'KML',
    'name' => t('KML Overlay'),
    'url' => $kml,
  );

  // Adds fullscreen button
  $map['behaviors'] = array(
    'fullscreen' => array(
      'id' => 'fullscreen',
      'type' => 'openlayers_behaviors_fullscreen',
      'layer' => 'kml_example',
    ),
    // Use the 'name' attrib from the KML file as tooltip
    'openlayers_views_tooltip_id' => array(
        'id' => 'openlayers_views_tooltip_id',
        'type' => 'openlayers_behaviors_tooltip',
        'layer' => 'kml_example',
        //'attribute' => 'Description', // could use description instead 
      ),
  );
  // Render Map
  $rendered_map = openlayers_render_map($map);

  return $rendered_map['themed'];
}
